export const ERROR = 'ERROR'


// #Accounts
export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const GET_BALANCES = 'GET_BALANCES'
export const BALANCES_RETURNED = 'BALANCES_RETURNED'

export const GET_BALANCES_LIGHT = 'GET_BALANCES_LIGHT'
export const BALANCES_LIGHT_RETURNED = 'BALANCES_LIGHT_RETURNED'

// #Exchange
export const GET_USD_PRICE = 'GET_USD_PRICE'
export const USD_PRICE_RETURNED = 'USD_PRICE_RETURNED'

export const GET_BEST_PRICE = 'GET_BEST_PRICE'
export const BEST_PRICE_RETURNED = 'BEST_PRICE_RETURNED'

export const SWAP = 'SWAP'
export const SWAP_RETURNED = 'SWAP_RETURNED'

export const GET_TOEKEN_DASHBOARD_SNAPSHOT = 'GET_TOEKEN_DASHBOARD_SNAPSHOT'
export const TOEKEN_DASHBOARD_SNAPSHOT_RETURNED = 'TOEKEN_DASHBOARD_SNAPSHOT_RETURNED'